/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @create date 2026-03-31
 * @modify date 2026-03-31
 * @desc Entity definitions used by the RAG metadata SQLite layer.
 */

/**
 * Stores syntax-level metadata for one indexed source file.
 */
export type SyntaxMetadataRecord = Readonly<{
  /** Workspace-relative file path. */
  relativePath: string;
  /** Parsed language identifier. */
  language: string;
  /** Last known file modification time in milliseconds. */
  mtimeMs: number;
  /** Imported module specifiers detected in the file. */
  imports: readonly string[];
  /** Exported bindings detected in the file. */
  exports: readonly string[];
  /** Symbol list extracted from the file. */
  symbols: readonly Readonly<{
    /** Symbol display name. */
    name: string;
    /** Symbol kind such as function, class, or type. */
    kind: string;
    /** Whether the symbol is exported. */
    exported: boolean;
    /** 1-based line number where the symbol starts. */
    line: number;
    /** Signature text used in retrieval and display. */
    signature: string;
  }>[];
}>;

/**
 * Stores semantic chunk metadata persisted alongside the semantic index.
 */
export type SemanticMetadataChunk = Readonly<{
  /** Stable chunk identifier. */
  id: string;
  /** Workspace-relative file path. */
  filePath: string;
  /** Human-readable chunk title. */
  title: string;
  /** Chunk classification such as code_symbol or doc_section. */
  kind: string;
  /** Optional symbol name represented by the chunk. */
  symbolName?: string;
  /** Whether the symbol is exported when applicable. */
  exported?: boolean;
  /** 1-based starting line of the chunk. */
  startLine?: number;
  /** 1-based ending line of the chunk. */
  endLine?: number;
  /** Short description used during retrieval. */
  description?: string;
  /** Origin of the generated description. */
  descriptionSource?: string;
  /** Last file modification time used for the chunk. */
  mtimeMs: number;
  /** Embedding model used for this chunk when available. */
  embeddingModel?: string;
  /** Timestamp when the chunk was indexed. */
  indexedAt: number;
}>;

/**
 * Stores structured tool evidence metadata for later retrieval hints.
 */
export type ToolEvidenceMetadata = Readonly<{
  /** Evidence identifier generated by the tool layer. */
  evidenceId: string;
  /** Tool name that produced the evidence. */
  toolName: string;
  /** Whether the tool call succeeded. */
  success: boolean;
  /** Whether the evidence is now considered stale. */
  stale: boolean;
  /** Timestamp when evidence was captured. */
  capturedAt: number;
  /** Concise evidence summary. */
  summary: string;
  /** Optional related file path. */
  targetPath?: string;
  /** Turn identifier that produced the evidence. */
  turnId: string;
}>;

/**
 * Represents one cached file/document read result.
 */
export type ReadCacheRecord = Readonly<{
  /** Workspace-relative or absolute file path used for cache lookup. */
  filePath: string;
  /** Source file mtime in milliseconds. */
  mtimeMs: number;
  /** Source file size in bytes. */
  sizeBytes: number;
  /** Read mode identifier such as full, chunk, or document_source. */
  readMode: string;
  /** Start offset used by the read. */
  offset: number;
  /** Character limit used by the read. */
  limit: number;
  /** Cached content body. */
  content: string;
  /** Optional serialized metadata payload. */
  metaJson?: string;
}>;

/**
 * Persisted summary of one completed task turn.
 */
export type TaskMemoryEntryRecord = Readonly<{
  /** Workspace identifier for the current project. */
  workspaceId: string;
  /** Turn identifier. */
  turnId: string;
  /** High-level turn classification. */
  turnKind: 'analysis' | 'implementation' | 'review' | 'validation' | 'repair';
  /** User request summarized for retrieval. */
  userIntent: string;
  /** Final assistant conclusion captured for the turn. */
  assistantConclusion: string;
  /** Optional JSON array of touched files. */
  filesJson?: string;
  /** Optional JSON array of related attachments. */
  attachmentsJson?: string;
  /** Confidence score attached to the conclusion. */
  confidence?: number;
  /** Freshness weight used during retrieval scoring. */
  freshnessScore?: number;
  /** Creation timestamp in milliseconds. */
  createdAt: number;
}>;

/**
 * Persisted structured issue/decision attached to a task memory entry.
 */
export type TaskMemoryFindingRecord = Readonly<{
  /** Finding identifier. */
  id: string;
  /** Parent entry turn identifier. */
  entryTurnId: string;
  /** Finding classification. */
  kind: 'accepted_finding' | 'review_finding' | 'validation_failure' | 'decision';
  /** Finding summary text. */
  summary: string;
  /** Optional related file path. */
  filePath?: string;
  /** Optional 1-based line number. */
  line?: number;
  /** Lifecycle status of the finding. */
  status?: 'open' | 'resolved' | 'dismissed';
  /** Creation timestamp in milliseconds. */
  createdAt: number;
}>;

/**
 * Retrieval-friendly summary of a task memory entry.
 */
export type TaskMemoryEntrySummary = Readonly<{
  /** Turn identifier. */
  turnId: string;
  /** High-level turn classification. */
  turnKind: string;
  /** User request summarized for retrieval output. */
  userIntent: string;
  /** Assistant conclusion summarized for retrieval output. */
  assistantConclusion: string;
  /** Files associated with the entry. */
  files: readonly string[];
  /** Attachments associated with the entry. */
  attachments: readonly string[];
  /** Confidence value persisted for the entry. */
  confidence: number;
  /** Freshness weighting value persisted for the entry. */
  freshnessScore: number;
  /** Creation timestamp in milliseconds. */
  createdAt: number;
}>;

/**
 * Retrieval-friendly summary of one finding linked to task memory.
 */
export type TaskMemoryFindingSummary = Readonly<{
  /** Finding identifier. */
  id: string;
  /** Parent entry turn identifier. */
  entryTurnId: string;
  /** Finding type label. */
  kind: string;
  /** Finding summary text. */
  summary: string;
  /** Optional related file path. */
  filePath?: string;
  /** Optional related line number. */
  line?: number;
  /** Current finding status. */
  status: string;
  /** Creation timestamp in milliseconds. */
  createdAt: number;
}>;

