/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @create date 2026-03-31
 * @modify date 2026-03-31
 * @desc Write and targeted-edit helpers for VS Code file tools.
 */

import fs from "node:fs";
import path from "node:path";
import { captureOriginal, trackFileWrite } from "../../runtime/session-tracker";
import type {
  EditFileRangeRequest,
  InsertFileAtLineRequest,
  MultiEditFileRange,
  ToolResult,
} from "../entities/file-tools";
import { resolveWorkspacePath, toDisplayPath } from "./path-read";
import {
  resolveInsertionLine,
  resolveRangeEditLocation,
  resolveUniqueRangeFromSnapshot,
  validateAnchoredRangeEdit,
  validateTargetedEditPreconditions,
} from "./targeted-edit";

function detectLineEnding(content: string): "\n" | "\r\n" {
  return content.includes("\r\n") ? "\r\n" : "\n";
}

function normalizeLineEndings(content: string): string {
  return content.replace(/\r\n/g, "\n").replace(/\r/g, "\n");
}

function splitLogicalLines(content: string): string[] {
  if (content.length === 0) {
    return [];
  }
  return normalizeLineEndings(content).split("\n");
}

function joinLogicalLines(
  lines: readonly string[],
  lineEnding: "\n" | "\r\n",
): string {
  return lines.join(lineEnding);
}

function normalizeSnapshotText(value: string | undefined): string | undefined {
  return typeof value === "string" ? normalizeLineEndings(value) : undefined;
}

function hasAnyField(
  edit: Readonly<Record<string, unknown>>,
  ...keys: readonly string[]
): boolean {
  return keys.some((key) => Object.prototype.hasOwnProperty.call(edit, key));
}

function readNumberField(
  edit: Readonly<Record<string, unknown>>,
  ...keys: readonly string[]
): number {
  for (const key of keys) {
    if (!Object.prototype.hasOwnProperty.call(edit, key)) {
      continue;
    }
    const value = edit[key];
    if (value === null || value === undefined || value === "") {
      continue;
    }
    const numeric = Number(value);
    if (Number.isFinite(numeric)) {
      return numeric;
    }
  }
  return Number.NaN;
}

function readNormalizedStringField(
  edit: Readonly<Record<string, unknown>>,
  ...keys: readonly string[]
): string {
  for (const key of keys) {
    if (!Object.prototype.hasOwnProperty.call(edit, key)) {
      continue;
    }
    const value = edit[key];
    return normalizeLineEndings(
      value === null || value === undefined ? "" : String(value),
    );
  }
  return "";
}

function countOccurrences(haystack: string, needle: string): number {
  if (!needle) {
    return 0;
  }
  return haystack.split(needle).length - 1;
}

/**
 * Counts total logical lines in a text payload.
 *
 * @param content Raw text content.
 * @returns Total number of newline-delimited lines.
 */
function countLines(content: string): number {
  return splitLogicalLines(content).length;
}

/**
 * Creates a brand-new file inside the workspace.
 *
 * @param workspaceRoot Absolute workspace root.
 * @param rawPath User-provided workspace-relative path.
 * @param content Full file content to write.
 * @returns Tool result describing the created file or the failure reason.
 */
export function writeFileTool(
  workspaceRoot: string,
  rawPath: string,
  content: string,
  overwriteExisting = false,
): ToolResult {
  try {
    if (!rawPath.trim()) {
      return {
        success: false,
        content: "",
        error:
          "write_file requires a non-empty path. Use the path parameter, or file_path/filePath/filepath alias if generated by the model.",
      };
    }
    const resolved = resolveWorkspacePath(workspaceRoot, rawPath);
    const existedBefore = fs.existsSync(resolved);
    if (existedBefore && !overwriteExisting) {
      return Object.freeze({
        success: false,
        content: "",
        error: `Refusing to overwrite existing file ${rawPath} with write_file. Use multi_edit_file_ranges for targeted edits. If this is a coherent whole-file repair, read the current file and call write_file again with overwrite_existing=true and the full corrected file content.`,
      });
    }
    captureOriginal(resolved);
    fs.mkdirSync(path.dirname(resolved), { recursive: true });
    fs.writeFileSync(resolved, content, "utf-8");
    trackFileWrite(resolved);

    return Object.freeze({
      success: true,
      content: `Written ${Buffer.byteLength(content, "utf-8")} bytes to ${toDisplayPath(resolved, workspaceRoot)}`,
      meta: Object.freeze({
        filePath: resolved,
        operation: existedBefore ? "overwrite" : "create",
        existedBefore,
        lineCount: countLines(content),
      }),
    });
  } catch (error) {
    return Object.freeze({ success: false, content: "", error: String(error) });
  }
}

/**
 * Performs exact-string replacement against one existing file.
 *
 * @param workspaceRoot Absolute workspace root.
 * @param rawPath User-provided workspace-relative path.
 * @param oldString Exact text that must currently exist in the file.
 * @param newString Replacement text to write.
 * @param replaceAll Whether all matching occurrences should be replaced.
 * @returns Tool result describing the applied replacement or the failure reason.
 */
export function editFileTool(
  workspaceRoot: string,
  rawPath: string,
  oldString: string,
  newString: string,
  replaceAll = false,
): ToolResult {
  try {
    const resolved = resolveWorkspacePath(workspaceRoot, rawPath);
    if (!fs.existsSync(resolved)) {
      return Object.freeze({
        success: false,
        content: "",
        error: `File not found: ${rawPath}`,
      });
    }

    captureOriginal(resolved);
    const original = fs.readFileSync(resolved, "utf-8");
    const lineEnding = detectLineEnding(original);
    const normalizedOriginal = normalizeLineEndings(original);
    const normalizedOldString = normalizeLineEndings(oldString);
    const normalizedNewString = normalizeLineEndings(newString);
    const hasExactMatch = original.includes(oldString);
    const hasNormalizedMatch = normalizedOriginal.includes(normalizedOldString);
    if (!hasExactMatch && !hasNormalizedMatch) {
      return Object.freeze({
        success: false,
        content: "",
        error: `old_string not found in ${rawPath}. It must match exactly, including whitespace.`,
      });
    }

    const occurrences = hasExactMatch
      ? countOccurrences(original, oldString)
      : countOccurrences(normalizedOriginal, normalizedOldString);
    if (occurrences > 1 && !replaceAll) {
      return Object.freeze({
        success: false,
        content: "",
        error: `old_string appears ${occurrences} times in ${rawPath}. Use replace_all=true or provide more context.`,
      });
    }

    const updatedNormalized = hasExactMatch
      ? normalizeLineEndings(
          replaceAll
            ? original.split(oldString).join(newString)
            : original.replace(oldString, newString),
        )
      : replaceAll
        ? normalizedOriginal
            .split(normalizedOldString)
            .join(normalizedNewString)
        : normalizedOriginal.replace(normalizedOldString, normalizedNewString);
    const updated =
      updatedNormalized.length > 0
        ? updatedNormalized.replace(/\n/g, lineEnding)
        : "";
    fs.writeFileSync(resolved, updated, "utf-8");
    trackFileWrite(resolved);

    const originalLines = splitLogicalLines(original);
    const updatedLines = splitLogicalLines(updated);
    const changedAt = originalLines.findIndex(
      (line, index) => line !== updatedLines[index],
    );
    const changedLineCount = Math.max(
      splitLogicalLines(oldString).length,
      splitLogicalLines(newString).length,
      1,
    );
    const changedRange =
      changedAt >= 0
        ? Object.freeze([
            { startLine: changedAt + 1, endLine: changedAt + changedLineCount },
          ])
        : Object.freeze([]);

    return Object.freeze({
      success: true,
      content: `Edited ${toDisplayPath(resolved, workspaceRoot)}${changedAt >= 0 ? ` starting at line ${changedAt + 1}` : ""}`,
      meta: Object.freeze({
        filePath: resolved,
        operation: "edit",
        existedBefore: true,
        replaceAll,
        occurrencesChanged: replaceAll ? occurrences : 1,
        changedLineRanges: changedRange,
      }),
    });
  } catch (error) {
    return Object.freeze({ success: false, content: "", error: String(error) });
  }
}

/**
 * Replaces one inclusive line range in an existing file using snapshot-safe guards.
 *
 * @param workspaceRoot Absolute workspace root.
 * @param rawPath User-provided workspace-relative path.
 * @param request Structured range-edit request plus snapshot evidence.
 * @returns Tool result describing the applied edit or the guard failure.
 */
export function editFileRangeTool(
  workspaceRoot: string,
  rawPath: string,
  request: EditFileRangeRequest,
): ToolResult {
  try {
    const resolved = resolveWorkspacePath(workspaceRoot, rawPath);
    const {
      startLine,
      endLine,
      newContent,
      expectedTotalLines,
      expectedRangeContent,
      anchorBefore,
      anchorAfter,
    } = request;
    if (!fs.existsSync(resolved)) {
      return Object.freeze({
        success: false,
        content: "",
        error: `File not found: ${rawPath}`,
      });
    }

    const preconditionError = validateTargetedEditPreconditions(
      rawPath,
      "range-edit",
      expectedTotalLines,
      {
        expectedRangeContent,
        expectedRangeContentProvided: typeof expectedRangeContent === "string",
        anchorBefore,
        anchorAfter,
      },
    );
    if (preconditionError) {
      return Object.freeze({
        success: false,
        content: "",
        error: preconditionError,
      });
    }

    captureOriginal(resolved);
    const original = fs.readFileSync(resolved, "utf-8");
    const lineEnding = detectLineEnding(original);
    const originalLines = splitLogicalLines(original);
    const normalizedExpectedRangeContent =
      normalizeSnapshotText(expectedRangeContent);
    const normalizedAnchorBefore = normalizeSnapshotText(anchorBefore);
    const normalizedAnchorAfter = normalizeSnapshotText(anchorAfter);
    const snapshot = {
      expectedRangeContent: normalizedExpectedRangeContent,
      expectedRangeContentProvided: typeof expectedRangeContent === "string",
      anchorBefore: normalizedAnchorBefore,
      anchorAfter: normalizedAnchorAfter,
    };
    const explicitRangeIsValid =
      Number.isFinite(startLine) &&
      Number.isFinite(endLine) &&
      startLine >= 1 &&
      endLine >= startLine;
    const initialRange = explicitRangeIsValid
      ? Object.freeze({ startLine, endLine })
      : resolveUniqueRangeFromSnapshot(originalLines, snapshot);
    if (!initialRange) {
      return Object.freeze({
        success: false,
        content: "",
        error: `Invalid line range for ${rawPath}. Provide 1-based start_line/end_line, or provide unique expected_range_content from a fresh read_file result so the tool can locate the range.`,
      });
    }
    const anchorError = validateAnchoredRangeEdit(
      rawPath,
      originalLines,
      initialRange.startLine,
      initialRange.endLine,
      snapshot,
    );
    if (anchorError) {
      return Object.freeze({ success: false, content: "", error: anchorError });
    }

    const resolvedRange = resolveRangeEditLocation(
      originalLines,
      initialRange.startLine,
      initialRange.endLine,
      snapshot,
    );
    if (!resolvedRange) {
      return Object.freeze({
        success: false,
        content: "",
        error: `Target range in ${rawPath} no longer matches the last read snapshot. Read the file again before editing.`,
      });
    }
    if (
      resolvedRange.startLine > originalLines.length ||
      resolvedRange.endLine > originalLines.length
    ) {
      return Object.freeze({
        success: false,
        content: "",
        error: `Resolved edit range ${resolvedRange.startLine}-${resolvedRange.endLine} is outside ${rawPath} (${originalLines.length} lines). Use insert_file_at_line for insertions.`,
      });
    }

    const replacementLines = splitLogicalLines(newContent);
    const updatedLines = [
      ...originalLines.slice(0, resolvedRange.startLine - 1),
      ...replacementLines,
      ...originalLines.slice(resolvedRange.endLine),
    ];
    const updated = joinLogicalLines(updatedLines, lineEnding);

    fs.writeFileSync(resolved, updated, "utf-8");
    trackFileWrite(resolved);

    return Object.freeze({
      success: true,
      content: `Edited ${toDisplayPath(resolved, workspaceRoot)} lines ${resolvedRange.startLine}-${resolvedRange.endLine}`,
      meta: Object.freeze({
        filePath: resolved,
        operation: "edit",
        existedBefore: true,
        changedLineRanges: Object.freeze([
          Object.freeze({
            startLine: resolvedRange.startLine,
            endLine: Math.max(
              resolvedRange.startLine,
              resolvedRange.startLine + replacementLines.length - 1,
            ),
          }),
        ]),
        rangeEdit: true,
        startLine: resolvedRange.startLine,
        endLine: resolvedRange.endLine,
        relocated:
          !explicitRangeIsValid ||
          resolvedRange.startLine !== startLine ||
          resolvedRange.endLine !== endLine,
        ...(Number.isFinite(expectedTotalLines) && expectedTotalLines! > 0
          ? { expectedTotalLines }
          : {}),
        ...(typeof normalizedExpectedRangeContent === "string" &&
        normalizedExpectedRangeContent.length > 0
          ? { expectedRangeContent: normalizedExpectedRangeContent }
          : {}),
        ...(typeof normalizedAnchorBefore === "string" &&
        normalizedAnchorBefore.length > 0
          ? { anchorBefore: normalizedAnchorBefore }
          : {}),
        ...(typeof normalizedAnchorAfter === "string" &&
        normalizedAnchorAfter.length > 0
          ? { anchorAfter: normalizedAnchorAfter }
          : {}),
      }),
    });
  } catch (error) {
    return Object.freeze({ success: false, content: "", error: String(error) });
  }
}

/**
 * Inserts content before one 1-based line using snapshot-safe guards.
 *
 * @param workspaceRoot Absolute workspace root.
 * @param rawPath User-provided workspace-relative path.
 * @param request Structured insert request plus snapshot evidence.
 * @returns Tool result describing the applied insert or the guard failure.
 */
export function insertFileAtLineTool(
  workspaceRoot: string,
  rawPath: string,
  request: InsertFileAtLineRequest,
): ToolResult {
  try {
    const resolved = resolveWorkspacePath(workspaceRoot, rawPath);
    const {
      line,
      contentToInsert,
      expectedTotalLines,
      anchorBefore,
      anchorAfter,
    } = request;
    if (!fs.existsSync(resolved)) {
      return Object.freeze({
        success: false,
        content: "",
        error: `File not found: ${rawPath}`,
      });
    }
    if (!Number.isFinite(line) || line < 1) {
      return Object.freeze({
        success: false,
        content: "",
        error: `Invalid line for ${rawPath}. line must be 1-based and >= 1.`,
      });
    }

    const preconditionError = validateTargetedEditPreconditions(
      rawPath,
      "insert",
      expectedTotalLines,
      {
        anchorBefore,
        anchorAfter,
      },
    );
    if (preconditionError) {
      return Object.freeze({
        success: false,
        content: "",
        error: preconditionError,
      });
    }

    captureOriginal(resolved);
    const original = fs.readFileSync(resolved, "utf-8");
    const lineEnding = detectLineEnding(original);
    const originalLines = splitLogicalLines(original);
    const normalizedAnchorBefore = normalizeSnapshotText(anchorBefore);
    const normalizedAnchorAfter = normalizeSnapshotText(anchorAfter);
    if (line > originalLines.length + 1) {
      return Object.freeze({
        success: false,
        content: "",
        error: `line ${line} is outside ${rawPath} (${originalLines.length} lines).`,
      });
    }
    const resolvedLine = resolveInsertionLine(originalLines, line, {
      anchorBefore: normalizedAnchorBefore,
      anchorAfter: normalizedAnchorAfter,
    });
    if (!resolvedLine) {
      return Object.freeze({
        success: false,
        content: "",
        error: `Insertion point in ${rawPath} no longer matches the last read snapshot. Read the file again before inserting.`,
      });
    }

    const insertedLines = splitLogicalLines(contentToInsert);
    const updatedLines = [...originalLines];
    updatedLines.splice(resolvedLine - 1, 0, ...insertedLines);
    fs.writeFileSync(
      resolved,
      joinLogicalLines(updatedLines, lineEnding),
      "utf-8",
    );
    trackFileWrite(resolved);

    return Object.freeze({
      success: true,
      content: `Inserted content into ${toDisplayPath(resolved, workspaceRoot)} before line ${resolvedLine}`,
      meta: Object.freeze({
        filePath: resolved,
        operation: "edit",
        existedBefore: true,
        changedLineRanges: Object.freeze([
          Object.freeze({
            startLine: resolvedLine,
            endLine: Math.max(
              resolvedLine,
              resolvedLine + insertedLines.length - 1,
            ),
          }),
        ]),
        insertEdit: true,
        startLine: resolvedLine,
        relocated: resolvedLine !== line,
        ...(typeof normalizedAnchorBefore === "string" &&
        normalizedAnchorBefore.length > 0
          ? { anchorBefore: normalizedAnchorBefore }
          : {}),
        ...(typeof normalizedAnchorAfter === "string" &&
        normalizedAnchorAfter.length > 0
          ? { anchorAfter: normalizedAnchorAfter }
          : {}),
      }),
    });
  } catch (error) {
    return Object.freeze({ success: false, content: "", error: String(error) });
  }
}

export function multiEditFileRangesTool(
  workspaceRoot: string,
  rawPath: string,
  edits: readonly MultiEditFileRange[],
  expectedTotalLines?: number,
): ToolResult {
  try {
    const resolved = resolveWorkspacePath(workspaceRoot, rawPath);
    if (!fs.existsSync(resolved)) {
      return Object.freeze({
        success: false,
        content: "",
        error: `File not found: ${rawPath}`,
      });
    }
    if (!Array.isArray(edits) || edits.length === 0) {
      return Object.freeze({
        success: false,
        content: "",
        error: `No edits provided for ${rawPath}.`,
      });
    }

    captureOriginal(resolved);
    const original = fs.readFileSync(resolved, "utf-8");
    const lineEnding = detectLineEnding(original);
    const originalLines = splitLogicalLines(original);
    const normalizedEdits = edits.map((edit, index) => {
      const rawEdit = edit as Readonly<Record<string, unknown>>;
      const startLine = readNumberField(rawEdit, "start_line", "startLine");
      const endLine = readNumberField(rawEdit, "end_line", "endLine");
      const hasNewContent = hasAnyField(rawEdit, "new_content", "newContent");
      if (!hasNewContent) {
        throw new Error(
          `Invalid range for edit ${index + 1} in ${rawPath}. Provide new_content for the replacement content.`,
        );
      }
      const snapshot = {
        expectedRangeContent: readNormalizedStringField(
          rawEdit,
          "expected_range_content",
          "expectedRangeContent",
        ),
        expectedRangeContentProvided: hasAnyField(
          rawEdit,
          "expected_range_content",
          "expectedRangeContent",
        ),
        anchorBefore: readNormalizedStringField(
          rawEdit,
          "anchor_before",
          "anchorBefore",
        ),
        anchorAfter: readNormalizedStringField(
          rawEdit,
          "anchor_after",
          "anchorAfter",
        ),
      };
      const preconditionError = validateTargetedEditPreconditions(
        rawPath,
        "multi-range-edit",
        expectedTotalLines,
        snapshot,
      );
      if (preconditionError) {
        throw new Error(`Edit #${index + 1}: ${preconditionError}`);
      }
      const explicitRangeIsValid =
        Number.isFinite(startLine) &&
        Number.isFinite(endLine) &&
        startLine >= 1 &&
        endLine >= startLine;
      const initialRange = explicitRangeIsValid
        ? Object.freeze({ startLine, endLine })
        : resolveUniqueRangeFromSnapshot(originalLines, snapshot);
      if (!initialRange) {
        throw new Error(
          `Invalid range for edit ${index + 1} in ${rawPath}. Provide 1-based start_line/end_line, or provide unique expected_range_content so the tool can locate the range.`,
        );
      }
      const resolvedRange = resolveRangeEditLocation(
        originalLines,
        initialRange.startLine,
        initialRange.endLine,
        snapshot,
      );
      if (!resolvedRange) {
        const outsideHint =
          explicitRangeIsValid &&
          (startLine > originalLines.length || endLine > originalLines.length)
            ? ` Requested range ${startLine}-${endLine} is outside the current ${originalLines.length}-line file and the provided snapshot could not be relocated.`
            : "";
        throw new Error(
          `Target range for edit #${index + 1} in ${rawPath} no longer matches the last read snapshot.${outsideHint} Read the file again before editing.`,
        );
      }
      if (
        resolvedRange.startLine > originalLines.length ||
        resolvedRange.endLine > originalLines.length
      ) {
        throw new Error(
          `Resolved edit range ${resolvedRange.startLine}-${resolvedRange.endLine} for edit #${index + 1} is outside ${rawPath} (${originalLines.length} lines). Use insert_file_at_line for insertions.`,
        );
      }
      return Object.freeze({
        startLine: initialRange.startLine,
        endLine: initialRange.endLine,
        newContent: readNormalizedStringField(
          rawEdit,
          "new_content",
          "newContent",
        ),
        resolvedStartLine: resolvedRange.startLine,
        resolvedEndLine: resolvedRange.endLine,
        ...snapshot,
      });
    });

    const resolvedEdits = normalizedEdits;

    const sorted = [...resolvedEdits].sort(
      (left, right) => right.resolvedStartLine - left.resolvedStartLine,
    );
    for (let index = 0; index < sorted.length - 1; index += 1) {
      const current = sorted[index];
      const next = sorted[index + 1];
      if (next.resolvedEndLine >= current.resolvedStartLine) {
        return Object.freeze({
          success: false,
          content: "",
          error: `Overlapping edit ranges detected in ${rawPath}.`,
        });
      }
    }

    for (const edit of resolvedEdits) {
      const anchorError = validateAnchoredRangeEdit(
        rawPath,
        originalLines,
        edit.resolvedStartLine,
        edit.resolvedEndLine,
        {
          expectedRangeContent: edit.expectedRangeContent,
          expectedRangeContentProvided: edit.expectedRangeContentProvided,
          anchorBefore: edit.anchorBefore,
          anchorAfter: edit.anchorAfter,
        },
      );
      if (anchorError) {
        return Object.freeze({
          success: false,
          content: "",
          error: anchorError,
        });
      }
    }

    let updatedLines = [...originalLines];
    for (const edit of sorted) {
      updatedLines = [
        ...updatedLines.slice(0, edit.resolvedStartLine - 1),
        ...splitLogicalLines(edit.newContent),
        ...updatedLines.slice(edit.resolvedEndLine),
      ];
    }

    fs.writeFileSync(
      resolved,
      joinLogicalLines(updatedLines, lineEnding),
      "utf-8",
    );
    trackFileWrite(resolved);

    return Object.freeze({
      success: true,
      content: `Edited ${toDisplayPath(resolved, workspaceRoot)} with ${normalizedEdits.length} targeted range edit(s)`,
      meta: Object.freeze({
        filePath: resolved,
        operation: "edit",
        existedBefore: true,
        multiRangeEdit: true,
        changedLineRanges: Object.freeze(
          resolvedEdits.map((edit) =>
            Object.freeze({
              startLine: edit.resolvedStartLine,
              endLine: Math.max(
                edit.resolvedStartLine,
                edit.resolvedStartLine +
                  splitLogicalLines(edit.newContent).length -
                  1,
              ),
            }),
          ),
        ),
        ...(Number.isFinite(expectedTotalLines) && expectedTotalLines! > 0
          ? { expectedTotalLines }
          : {}),
      }),
    });
  } catch (error) {
    return Object.freeze({
      success: false,
      content: "",
      error: error instanceof Error ? error.message : String(error),
    });
  }
}
